- hosts: localhost
  name: Set dotfiles symlinks
  gather_facts: False
  tasks:
    - name: Ensure directories exist for dotfiles
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/.config/alacritty
    
    - name: Ensure configs are symlinked
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - {src: ~/.dotfiles/macos/alacritty.yml, dest: ~/.config/alacritty/alacritty.yml}
        - {src: ~/.dotfiles/macos/zshrc, dest: ~/.zshrc}
        - {src: ~/.dotfiles/macos/p10k.zsh, dest: ~/.p10k.zsh}

    - name: Ensure base empty files exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
      with_items:
        - ~/.zshrc.extra
        - ~/.hushlogin
