- hosts: localhost
  name: Set dotfiles symlinks
  gather_facts: False
  tasks:
    - name: Ensure directories exist for dotfiles
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/.config/alacritty
        - ~/.hammerspoon
    
    - name: Ensure configs are symlinked
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - {src: ~/.dotfiles/wezterm/wezterm.lua, dest: ~/.wezterm.lua}
        - {src: ~/.dotfiles/zsh/zshrc, dest: ~/.zshrc}
        - {src: ~/.dotfiles/zsh/p10k.zsh, dest: ~/.p10k.zsh}
        - {src: ~/.dotfiles/hammerspoon/hammerspoon.init.lua, dest: ~/.hammerspoon/init.lua}

    - name: Ensure base empty files exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
      with_items:
        - ~/.zshrc.extra
        - ~/.hushlogin
