- hosts: localhost
  name: Install Homebrew
  gather_facts: False
  tasks:
    - name: Ensure taps are present via homebrew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - homebrew/cask-fonts

    - name: Ensure packages are present via homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: latest
        install_options: "appdir=/Applications"
      with_items:
        - alacritty
        - alt-tab
        - beardedspice
        - bettertouchtool
        - docker
        - font-fira-code-nerd-font
        - google-chrome
        - itsycal
        - little-snitch
        - rectangle
        - slack
        - spotify

    - name: Ensure packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - autojump
        - direnv
        - eza 
        - fzf
        - git
        - git-delta
        - golang
        - gpg
        - gron
        - htop
        - hyperfine
        - imagemagick
        - jq
        - just
        - neovim
        - nodejs
        - openssh
        - pyenv
        - ripgrep
        - rust
        - tig
        - tmux
        - wget
        - zsh
    - name: Ensure packages are absent
      community.general.homebrew:
        name: "{{ item }}"
        state: absent
      with_items:
        - exa  # Replaced with eza
