- hosts: localhost
  name: Install Homebrew
  gather_facts: False
  tasks:
    - name: Include common variables
      include_vars: vars/common.yaml

    - name: Include host specific variables
      include_vars: vars/{{ codename }}.yaml

    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: yes

    - name: Ensure common packages are present via homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: latest
        install_options: "appdir=/Applications"
      loop: "{{ homebrew_cask_packages }}"

    - name: Ensure host specific packages are present via homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: latest
        install_options: "appdir=/Applications"
      loop: "{{ host_homebrew_cask_packages | default([]) }}"

    - name: Ensure common packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ homebrew_packages }}"

    - name: Ensure host specific packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ host_homebrew_packages | default([]) }}"

    - name: Ensure packages are absent
      community.general.homebrew:
        name: "{{ item }}"
        state: absent
      loop: "{{ homebrew_packages_to_remove }}"
