- hosts: localhost
  name: Set up Neovim with LazyVim
  gather_facts: false
  tasks:
    - name: Check if ~/.config/nvim exists
      ansible.builtin.stat:
        path: "~/.config/nvim"
      register: nvim_stat

    - name: Backup existing ~/.config/nvim if it is not a symlink
      ansible.builtin.command: mv ~/.config/nvim ~/.config/nvim.bak
      when: nvim_stat.stat.exists and not nvim_stat.stat.islnk

    - name: Ensure ~/.config/nvim is symlinked to lazyvim config
      ansible.builtin.file:
        src: "~/.dotfiles/lazyvim"
        dest: "~/.config/nvim"
        state: link
        force: true
