- hosts: localhost
  name: Set up neovim
  gather_facts: False
  tasks:
    - name: Ensure directories exist for nvim
      ansible.builtin.file:
        path: "~/.config/nvim"
        state: directory

    - name: Ensure configs are symlinked
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - {src: ~/.dotfiles/nvim/init.lua, dest: ~/.config/nvim/init.lua}
        - {src: ~/.dotfiles/nvim/lua, dest: ~/.config/nvim/lua}

    - name: Ensure paq-nvim up to date
      ansible.builtin.git:
        repo: "https://github.com/savq/paq-nvim.git"
        dest: "~/.local/share/nvim/site/pack/paqs/start/paq-nvim"
        update: true
        depth: 1

    - name: Create temporary init.lua for initial install
      ansible.builtin.copy:
        content: "require('pack')"
        dest: /tmp/init.lua

    - name: Run PaqInstall
      ansible.builtin.shell: nvim -E -u /tmp/init.lua +PaqInstall +q
