require('options')

require('pack')

require('plugins.compe')
require('plugins.gitsigns')
--require('plugins.lspconfig')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.treesitter')
require('plugins.bufferline')
require('plugins.common')
require('plugins.simple')
require('plugins.neotest')
require('plugins.hop')
require('plugins.lsp')
