require('options')

require('pack')

require('plugins.airline')
require('plugins.compe')
require('plugins.gitsigns')
require('plugins.indentline')
require('plugins.lspconfig')
require('plugins.lspkind')
require('plugins.poet')
require('plugins.rooter')
require('plugins.telescope')
require('plugins.rust')
require('plugins.theme')
require('plugins.toggleterm')
require('plugins.treesitter')
require('plugins.vimvisualmulti')
