require('impatient')
require('options')

require('pack')

require('plugins.cmp')
require('plugins.gitsigns')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.treesitter')
require('plugins.bufferline')
require('plugins.common')
require('plugins.simple')
--require('plugins.neotest')
require('plugins.hop')
require('plugins.lsp')
require('plugins.copilot')
