litime

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

export PATH="/usr/local/opt/pyenv/shims:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="/usr/local/opt/libpq/bin:$PATH"

# Env variables
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git autojump zsh-syntax-highlighting zsh-completions zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
  compinit
done

compinit -C

export EDITOR=nvim

# Pyenv
eval "$(pyenv init -)"

# Direnv
eval "$(direnv hook zsh osx brew)"
export DIRENV_LOG_FORMAT=""

# Aliases
alias vim=nvim
alias ls=lsd
alias rg="rg -S"
alias rgff="rg --files -g"
alias p=poetry
alias ,,='git rev-parse --git-dir >/dev/null 2>&1 && cd `git rev-parse --show-toplevel` || echo "Not in git repo"'
alias git=hub
alias :q='exit'
alias vi='vi -u NONE'
alias gcan="git commit --amend --no-edit"
alias greb="git rebase origin/master"
alias pods="kubectl get pods"
alias nodes="kubectl get nodes"

# Utils
sleep-in() {echo "Sleeping laptop in $1 minutes..." && sleep $((60 * $1)) && pmset sleepnow}
alias flushdns="sudo killall -HUP mDNSResponder"

# Make that history biiiig
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source ~/.zshrc.extra

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
