set dotenv-load 

alias brew := homebrew

# Run the full set of playbooks
full:
  @ansible-playbook -e "codename=${CODENAME}" full.yaml

# Update and ensure packages installed with homebrew
homebrew:
  @ansible-playbook -e "codename=${CODENAME}" playbooks/homebrew.yaml

# Install dockutil and use it to arrange the dock
dock:
  @ansible-playbook -e "codename=${CODENAME}" playbooks/dock.yaml

# Set up neovim
nvim:
  @ansible-playbook -e "codename=${CODENAME}" playbooks/nvim.yaml

# Set up tmux
tmux:
  @ansible-playbook -e "codename=${CODENAME}" playbooks/tmux.yaml
