- hosts: localhost
  name: Set dotfiles symlinks
  gather_facts: False
  tasks:
    - name: Ensure directories exist for dotfiles
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/.config/alacritty
        - ~/.config/nvim
    
    - name: Ensure configs are symlinked
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - {src: ~/Projects/dotfiles/tmux.conf, dest: ~/.tmux.conf}
        - {src: ~/Projects/dotfiles/macos/alacritty.yml, dest: ~/.config/alacritty/alacritty.yml}
        - {src: ~/Projects/dotfiles/macos/zshrc, dest: ~/.zshrc}
        - {src: ~/Projects/dotfiles/macos/p10k.zsh, dest: ~/.p10k.zsh}
        - {src: ~/Projects/dotfiles/nvim/init.lua, dest: ~/.config/nvim/init.lua}
        - {src: ~/Projects/dotfiles/nvim/lua, dest: ~/.config/nvim/lua}

    - name: Ensure .zshrc.extra exists
      ansible.builtin.file:
        path: ~/.zshrc.extra
        state: touch
