export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="/usr/local/opt/libpq/bin:$PATH"

litime --main-formatting "dimmed white" --author-formatting "intense white"

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

# Env variables
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PYTHONDONTWRITEBYTECODE=1
export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-syntax-highlighting zsh-completions zsh-autosuggestions fzf)

source $ZSH/oh-my-zsh.sh

autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

export EDITOR=nvim

# Direnv
eval "$(direnv hook zsh osx brew)"
export DIRENV_LOG_FORMAT=""

# Aliases
alias vim="nvim -u ~/.config/nvim/init.lua"
alias ls="eza --git"
alias rg="rg -S"
alias rgff="rg --files -g"
alias p=poetry
alias ,,='git rev-parse --git-dir >/dev/null 2>&1 && cd `git rev-parse --show-toplevel` || echo "Not in git repo"'
alias :q='exit'
alias vi='nvim -u NONE'
alias gcan="git commit --amend --no-edit"
alias greb="git rebase origin/master"
alias dc="docker-compose"
alias flushdns="sudo killall -HUP mDNSResponder"

source ~/.zshrc.extra

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(atuin init zsh --disable-up-arrow)"
eval "$(zoxide init zsh --cmd j)"
