export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/local/opt/pyenv/shims:$PATH"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="/usr/local/opt/libpq/bin:$PATH"

litime --main-colour white --author-colour bright-white

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

# Env variables
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PYTHONDONTWRITEBYTECODE=1
export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git autojump zsh-syntax-highlighting zsh-completions zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
  compinit
done

compinit -C

export EDITOR=nvim

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# Direnv
eval "$(direnv hook zsh osx brew)"
export DIRENV_LOG_FORMAT=""

# Aliases
alias vim="nvim -u ~/.config/nvim/init.lua"
alias ls="exa --git"
alias rg="rg -S"
alias rgff="rg --files -g"
alias p=poetry
alias ,,='git rev-parse --git-dir >/dev/null 2>&1 && cd `git rev-parse --show-toplevel` || echo "Not in git repo"'
alias :q='exit'
alias vi='nvim -u NONE'
alias gcan="git commit --amend --no-edit"
alias greb="git rebase origin/master"
alias pods="kubectl get pods"
alias nodes="kubectl get nodes"
alias dc="docker-compose"
alias flushdns="sudo killall -HUP mDNSResponder"

function pyb () {
  pyboard --device `serpico -p` $*
}

# Utils
sleep-in() {echo "Sleeping laptop in $1 minutes..." && sleep $((60 * $1)) && pmset sleepnow}

# Make that history biiiig
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups

source ~/.zshrc.extra

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
