# theme = "plain"
# theme = "gruvbox-light"
theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "tailscale\\d+"]
interface_name_include = []
ap_format = "{ssid} {strength}"
device_format = "{icon}{ap}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{average}"
chip = "coretemp-isa-0000"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
hide_when_empty = true

[[block]]
block = "custom"
command = "/usr/bin/python3 /home/axel/.watson.py"
interval = 10
json = true

[[block]]
block = "battery"
interval = 10
warning = 40
critical = 20
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
