litime --main-colour white --author-colour bright-white

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

export PATH="/usr/local/opt/pyenv/shims:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/.env:$PATH"

# Env variables
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PYTHONDONTWRITEBYTECODE=1
export NVM_LAZY_LOAD=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('nvim')

vim () {
	unset -f nvim > /dev/null 2>&1
	_zsh_nvm_load
	nvim "$@"
}


ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git autojump zsh-syntax-highlighting zsh-completions zsh-autosuggestions zsh-nvm)

source $ZSH/oh-my-zsh.sh

autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
  compinit
done

compinit -C

export EDITOR=nvim

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

eval "$(direnv hook zsh)"


# Aliases
alias ls="exa --git"
alias rg="rg -S"
alias rgff="rg --files -g"
alias p=poetry
alias ,,='git rev-parse --git-dir >/dev/null 2>&1 && cd `git rev-parse --show-toplevel` || echo "Not in git repo"'
alias git=hub
alias :q='exit'
alias vi='nvim -u NONE'
alias gcan="git commit --amend --no-edit"
alias greb="git rebase origin/master"
alias ci="unbuffer hub ci-status -v | cut -f1-2"
alias dc="docker-compose"
alias pbcopy="xclip -sel clip"

# Make that history biiiig
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups

source ~/.zshrc.extra

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh
